spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/mulika_dev
spring.datasource.username=postgres
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
