"""create invoice line item table

Revision ID: 16e7bcfdbf05
Revises: e5fc493667b6
Create Date: 2026-07-03 10:39:05.637654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e7bcfdbf05'
down_revision: Union[str, Sequence[str], None] = 'e5fc493667b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('hsn_code', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_line_items')
    # ### end Alembic commands ###
