"""make product_id nullable in line items

Revision ID: 799e8110219b
Revises: b2e8abfe49e8
Create Date: 2026-07-05 14:22:50.286433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799e8110219b'
down_revision: Union[str, Sequence[str], None] = 'b2e8abfe49e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_line_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_line_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
