"""add customer fields to invoices table

Revision ID: b2e8abfe49e8
Revises: 16e7bcfdbf05
Create Date: 2026-07-05 13:34:13.651976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e8abfe49e8'
down_revision: Union[str, Sequence[str], None] = '16e7bcfdbf05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add all columns as nullable first
    # (existing rows need a value before we can enforce NOT NULL)
    op.add_column('invoices', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('customer_gstin', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('customer_email', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('customer_phone', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('customer_address', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('customer_city', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('customer_state', sa.String(), nullable=True))

    # Step 2: Fill existing rows with a placeholder value
    op.execute("UPDATE invoices SET customer_name = 'Legacy Customer' WHERE customer_name IS NULL")

    # Step 3: Now enforce NOT NULL on customer_name only
    op.alter_column('invoices', 'customer_name', nullable=False)

    # Step 4: Make customer_id nullable (existing rows keep their value)
    op.alter_column('invoices', 'customer_id', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('invoices', 'customer_state')
    op.drop_column('invoices', 'customer_city')
    op.drop_column('invoices', 'customer_address')
    op.drop_column('invoices', 'customer_phone')
    op.drop_column('invoices', 'customer_email')
    op.drop_column('invoices', 'customer_gstin')
    op.drop_column('invoices', 'customer_name')
    # ### end Alembic commands ###
